In [1]:
# TASK 1
#Consider 2-d array and Convert all the elements of a num py array from float to Bool datatype.
import numpy as np

# Create a 2D float array
float_array = np.array([[1.2, 3.4, 5.6],
                       [7.8, 9.0, 11.12]])
bool_array = float_array.astype(bool)

print("Original float array:")
print(float_array)

print("\nConverted bool array:")
print(bool_array)

Original float array:
[[ 1.2   3.4   5.6 ]
 [ 7.8   9.   11.12]]

Converted bool array:
[[ True  True  True]
 [ True  True  True]]


In [2]:
#TASK 2
#•add the element 55 at position 2.
#•Print the updated array after the insertion.
def insert_element(array, element, position):

  if position < 0 or position > len(array):
    raise ValueError("Invalid position.")

  array.insert(position, element)
  return array
my_array = [10, 20, 30, 40]
new_array = insert_element(my_array, 55, 2)

#updated array
print(new_array)

[10, 20, 55, 30, 40]


In [3]:
#TASK 3
#Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers, for example: 0, 2, 4
import numpy as np
array = np.arange(0, 101, 2)

print(array)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [4]:
#TASK 4
#Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array)
import numpy as np


matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.matmul(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nResult of matrix multiplication:")
print(result)

Matrix 1:
[[1 2]
 [3 4]]

Matrix 2:
[[5 6]
 [7 8]]

Result of matrix multiplication:
[[19 22]
 [43 50]]


In [5]:
#TASK 5
#Consider a 1-d array and check whether the specific number is present or not?
def is_number_present(array, number):
  

  for element in array:
    if element == number:
      return True
  return False

# Create an example array
my_array = [10, 20, 30, 40, 50]

# Check if the number 30 is present
result = is_number_present(my_array, 30)

if result:
  print("The number is present in the array.")
else:
  print("The number is not present in the array.")

The number is present in the array.
